export const AUTHLOADING="AUTHLOADING"
export const AUTHFAILURE="AUTHFAILURE"
export const AUHTSUCCESS="AUHTSUCCESS"


export const LOGINLOADING="LOGINLOADING"
export const LOGINFAILURE="LOGINFAILURE"
export const LOGINSUCCESS="LOGINSUCCESS"


export const LOGOUTSUCCESS="LOGSUCCESS";


export const RESETSUCCESS="RESETSUCCESS";
export const RESETFAILURE="RESETFAILURE";